### ISSUE TITLE
User interface to import the data

### ISSUE THREAD

**Issue by Chardonneaur** [deadda7a/Matomo-VIP-Detector#2]
Hello,
This is just an enhancement, but would it be possible to have a user interface to import the IP addresses and associated names?
Thank you,

**Comment by deadda7a** [comment]
Hey,

this is certainly a good idea and I'm also planning to do that, I just implemented the CLI importer first because I import the JSON via a Cronjob so I needed it to be done first (and it was easier :))

Sebastian Elisa

**Comment by Chardonneaur** [comment]
My frustration was that on a shared host we don t have ssh access.

**Comment by deadda7a** [comment]
Closed with release 3.0.0 :)
