### ISSUE TITLE
Plugin is unable to import properly formated JSON file

### ISSUE THREAD

**Issue by sledzik1984** [deadda7a/Matomo-VIP-Detector#4]
`# ./console vipdetector:import-data /root/vip.json
Loading from file /root/vip.json
ERROR     [08:43:24] 2832229  Uncaught exception: ParseError: syntax error, unexpected '|', expecting ';' or '{' in /home/matomo/plugins/VipDetector/Dao/DatabaseMethods.php:42
Stack trace:
#0 /home/matomo/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /home/matomo/plugins/VipDetector/Commands/ImportData.php(46): spl_autoload_call()
#3 /home/matomo/core/Plugin/ConsoleCommand.php(110): Piwik\Plugins\VipDetector\Commands\ImportData->doExecute()
#4 /home/matomo/vendor/symfony/console/Command/Command.php(298): Piwik\Plugin\ConsoleCommand->execute()
#5 /home/matomo/core/Plugin/ConsoleCommand.php(125): Symfony\Component\Console\Command\Command->run()
#6 /home/matomo/vendor/symfony/console/Application.php(1040): Piwik\Plugin\ConsoleCommand->run()
#7 /home/matomo/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /home/matomo/core/Console.php(106): Symfony\Component\Console\Application->doRun()
#9 [internal function]: Piwik\Console->originDoRun()
#10 /home/matomo/core/Console.php(145): call_user_func()
#11 /home/matomo/core/Access.php(670): Piwik\Console->Piwik\{closure}()
#12 /home/matomo/core/Console.php(146): Piwik\Access::doAsSuperUser()
#13 /home/matomo/core/Console.php(85): Piwik\Console->doRunImpl()
#14 /home/matomo/vendor/symfony/console/Application.php(171): Piwik\Console->doRun()
#15 /home/matomo/console(32): Symfony\Component\Console\Application->run()
#16 {main}
Uncaught exception in /home/matomo/plugins/VipDetector/Dao/DatabaseMethods.php line 42:
syntax error, unexpected '|', expecting ';' or '{'
`

**Comment by deadda7a** [comment]
Hi,

thank you for the report, can you tell me a bit about your environment? Because it seems you're using the 5.X version on PHP 7 (Since union types are only supported in PHP 8, which is also recommended for 5.X)?

Sebastian Elisa

**Comment by sledzik1984** [comment]
I've managed that. Server used PHP 7.4 from Debian Repo. 
It would be great to have info about minimal PHP version in plugin description :)

**Comment by deadda7a** [comment]
Yes that would have been smart D:

But anyway since this is a thing that is not needed for the functionality of the plugin and is just for better code, I will see if I just "backport" it to PHP 7.

**Comment by deadda7a** [comment]
I've removed the parts that caused this issue. Release 2.0.1 works with 7.3 according to my tests.

Todo: Unit tests.
